services:
  redis:
    image: redis:7.4.1-alpine3.20
    container_name: lyzer-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data-dev:/data
    networks:
      - lyzer-network

  api:
    build:
      context: Backend/Lyzer
      dockerfile: Docker/Dev/Dockerfile
    container_name: lyzer-api
    env_file:
      - .env.dev
    ports:
      - 8080:8080
    networks:
      - lyzer-network
    develop:
      watch:
        - action: sync
          path: ./Backend/Lyzer
          target: /app
          ignore:
            - bin/
            - obj/
        - action: rebuild
          path: ./Backend/Lyzer/Lyzer.csproj

  docs:
    build:
      context: Docs
    container_name: lyzer-docs
    ports:
      - 8000:8000
    networks:
      - lyzer-network
    develop:
      watch:
        - action: sync
          path: ./Docs
          target: /app
        - action: rebuild
          path: ./Docs/requirements.txt

  frontend:
    build:
      context: ./Frontend
      dockerfile: docker/dev/Dockerfile
    container_name: lyzer-frontend
    ports:
      - "5173:5173"
    networks:
      - lyzer-network
    develop:
      watch:
        - action: sync
          path: ./Frontend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./Frontend/package.json
        - action: rebuild
          path: ./Frontend/package-lock.json

networks:
  lyzer-network:
    driver: bridge

volumes:
  redis-data-dev:
    external: false
