site_name: Lyzer
site_url: 'https://littleclumsy.github.io/Lyzer/'
plugins:
  - search

extra:
  version:
    provider: mike

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.superfences"

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.path
    - navigation.top
  palette: 
    - scheme: default
      primary: black
      accent: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/extra.css

nav:
  - Home: index.md
  - Development:
    - Getting Started: dev/index.md
  - Architecture, code and patterns:
    - Overview: architecture/overview.md
    - API/Backend:
      - General Structure: architecture/backend/overview.md
      - How we utilize redis: architecture/backend/caching.md
    - Frontend:
      - General Structure: architecture/frontend/overview.md
  - Roadmap/Milestones:
    - Release 0.1.0: roadmap/0-1-0.md
