site_name: Lyzer
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.superfences"
theme:
  name: material
  features:
    - content.code.copy
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Development:
    - Getting Started: dev/index.md
  - Architecture, code and patterns:
    - Overview: dev/architecture.md
    - How we utilize redis: backend/caching.md
    - API/Backend:
      - General Structure: backend/architecture.md