release:
	dotnet publish --configuration Release --output dist/

up:
	dotnet run Project --environment Development --launch-profile https

build:
	dotnet build

clean:
	rm -rf dist/

format:
	dotnet format Lyzer-BE.csproj