name: Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  be-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend/Lyzer
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          cache: true
      - name: Install dependencies
        run: dotnet restore
      - name: Build app
        run: dotnet build
