name: Lint

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  be-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          cache: true
          cache-dependency-path: Backend/Lyzer
      - name: Install dependencies
        run: dotnet restore
      - name: Check formatting
        run: dotnet format --verify-no-changes

  fe-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Frontend
        
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.11.0'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint app
        run: npm run lint
