on:
  push:
    branches:
      - trunk

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          token: ${{secrets.GITHUB_TOKEN}}
          default-branch: trunk
      - name: Build image
        if: ${{ steps.release.outputs.releases_created }}
        run: docker build -t lyzer:latest Lyzer-BE/
      - name: Install doctl
        if: ${{ steps.release.outputs.releases_created }}
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        if: ${{ steps.release.outputs.releases_created }}
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        if: ${{ steps.release.outputs.releases_created }}
        run: docker tag lyzer:latest \
          registry.digitalocean.com/lyzer-cr/lyzer:latest
      - name: Push image to DO Container Registry
        if: ${{ steps.release.outputs.releases_created }}
        run: docker push registry.digitalocean.com/lyzer-cr/lyzer:latest
      - name: Release asset to Github Releases
        if: ${{ steps.release.outputs.releases_created }}
        working-directory: Lyzer-BE/
        run: |
          dotnet publish --configuration Release --output dist/
          zip -r UbuntuRelease.zip dist/
          gh release create ${{ steps.release.outputs.tag_name }} UbuntuRelease.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
